# Generated by Django 4.2.5 on 2023-11-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimages_product_image_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='shop/static/uploads/products'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='uploads/products/images/'),
        ),
    ]
