# Generated by Django 4.2.5 on 2023-11-03 07:59

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='static/product_images'),
        ),
    ]
