# Generated by Django 4.2.5 on 2023-11-03 08:11

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='static/product_images', verbose_name='Image'),
        ),
    ]
