# Generated by Django 4.2.5 on 2023-11-04 10:03

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productimage_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='product_images'),
        ),
    ]
