# Generated by Django 4.2.5 on 2023-11-04 10:53

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='', upload_to='product_images/main_images'),
            preserve_default=False,
        ),
    ]
