# Generated by Django 4.2.5 on 2023-11-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
